### ISSUE TITLE
MIB Models appear in ietf and MIB models

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/ncc#14]
Looks like there are two different types of MIB models.  One lot appear under IETF and the other under MIB models.

IETF Models:
        CISCO-CBP-TC-MIB (urn:ietf:params:xml:ns:yang:smiv2:CISCO-CBP-TC-MIB)
        RSVP-MIB (urn:ietf:params:xml:ns:yang:smiv2:RSVP-MIB)
        ATM-FORUM-TC-MIB (urn:ietf:params:xml:ns:yang:smiv2:ATM-FORUM-TC-MIB)
        CISCO-CBP-TARGET-TC-MIB (urn:ietf:params:xml:ns:yang:smiv2:CISCO-CBP-TARGET-TC-MIB)
        MPLS-LSR-STD-MIB (urn:ietf:params:xml:ns:yang:smiv2:MPLS-LSR-STD-MIB)
        CISCO-ATM-PVCTRAP-EXTN-MIB (urn:ietf:params:xml:ns:yang:smiv2:CISCO-ATM-PVCTRAP-EXTN-MIB)

MIB Models:
        SNMPv2-MIB (http://tail-f.com/ns/mibs/SNMPv2-MIB/200210160000Z)
        SNMP-NOTIFICATION-MIB (http://tail-f.com/ns/mibs/SNMP-NOTIFICATION-MIB/200210140000Z)
        SNMP-MPD-MIB (http://tail-f.com/ns/mibs/SNMP-MPD-MIB/200210140000Z)
        SNMP-VIEW-BASED-ACM-MIB (http://tail-f.com/ns/mibs/SNMP-VIEW-BASED-ACM-MIB/200210160000Z)

**Comment by einarnn** [comment]
I chose to classify first based on the IETF urn. The other modules are not standards-based, but are from (as you see) Tail-F. Maybe if I classify the "MIB Models" as "Tail-F MIB Models"?

**Comment by aradford123** [comment]
It might be a little confusing that CISCO-CBP-TC is treated as ietf.
I understand the nuance as to why (ietf is about the general translation of a MIB, not the contents of it), but i am sure many will ask that question.

**Comment by einarnn** [comment]
So, those ones are bugs that will be tidied up (on XR we are starting to do validation of stuff like this and get bugs raised). The alternative is to not bother with model classification at all, just present a sorted list of models.

Any preference?

**Comment by einarnn** [comment]
Fixed in #32.
