### ISSUE TITLE
How to apply a model to multiple devices?

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/ncc#15]
I would like to make a change to many devices.  e.g. change ntp server many devices.

Need to have a way to specify a device list in a simple way.

**Comment by einarnn** [comment]
`ncc` is primarily intended to be a "craft tool". Extending to deal with lists of devices and more runs the risk of turning it into something it is not intended to be. Should we close off this issue?

**Comment by aradford123** [comment]
Yes.
