### ISSUE TITLE
do we need to make vars and templates explicit?

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/ncc#16]
Currently it is not obvious (unless you read documentation) which are templates and vars
11:28 $ python ncc.py --list-templates
Edit-config templates:
  add_neighbor                           <<-- template name
    DESCRIPTION                          <<-- substitution
    NEIGHBOR_ADDR
    REMOTE_AS
  add_static_route_default
  del_neighbor
    NEIGHBOR_ADDR

Should we say something like:
Template: add_neigbor
 {"DESCRIPTION" :"", "NEIGHBOR_ADDR" :"", "REMOTE_AS":""}

That way I have a pre-filled JSON template to fill in too?

**Comment by aradford123** [comment]
Could even have it on one line?
Template: add_neigbor: {"DESCRIPTION" :"", "NEIGHBOR_ADDR" :"", "REMOTE_AS":""}

**Comment by einarnn** [comment]
Yep, seems like a plan! Assign it to yourself if you want to do it! 😜

**Comment by aradford123** [comment]
How do you like this?
./ncc.py   --list-templates Edit-config templates:
  add_neighbor :{ "DESCRIPTION" : "","NEIGHBOR_ADDR" : "","REMOTE_AS" : "" }
  add_static_route_default
  class_dscp31_cr
  class_dscp31_del
  classmap_delete_einarnn_all
  classmap_einarnn_3
  classmap_einarnn_4
  classmap_einarnn_5
  classmap_einarnn_6
  del_neighbor :{ "NEIGHBOR_ADDR" : "" }
  del_static_route_default
  delete_autoneg
  delete_ebgp_multihop_enabled
  delete_l2vpn
  empty_l2vpn
  foo1_add_static_route_default
  foo2_add_static_route_default
  ietf-cr-loopback :{ "INTF_NAME" : "" }
  ietf-intf-add-ipv4 :{ "INTF_NAME" : "" }
  l2vpn_bdgroups_cr
  l2vpn_bdgroups_del
  lldp-basic-and-del
  lldp-basic
  lldp-del
  no_shut
  oc-set-descr-broken
  oc-set-descr
  oc_basic
  policy_test_cr
  policy_test_del
  restconf-enable :{ "BRIDGE_IP" : "","RC_HTTPS_PORT" : "","RC_HTTP_PORT" : "" }
  set_autoneg_override
  set_autoneg_true
  set_ebgp_multihop_enabled_false
  set_ebgp_multihop_enabled_true
  shut
  simple_ospf
  telem-cr
  telem-del-ipv6-fails
  telem-del-ipv6-works
  xe-enable-polling
  xxx
  xxx_del
