### ISSUE TITLE
Should params files be in a fixed location also:

### ISSUE THREAD

**Issue by einarnn** [CiscoDevNet/ncc#5]
from aradford123:

> I was thinking params files should be under snippets?
>
```
snippets-xe/
├── editconfigs
│   ├── 00-oper-data-enable-16.4.tmpl
│   ├── 00-oper-data-enable.tmpl
│   ├── 00-snmp-config.tmpl
│   ├── 01-oper-data-disable.tmpl
│   ├── 01-snmp-config-disable
│   └── native-intf-vlan-change.tmpl
└── filters
└── params
│   ├── interface-params
```

**Comment by einarnn** [comment]
Hmm. Not quite so sure about this one. I can see a certain logic to that, but would also want to be able to specify a space file, rather than one that lives in a semi-fixed location.

Maybe:

* ```--params-file=foo``` Look in params directory under snippets
* ```--params-file=./foo``` Look in current directory ncc.py is being run from
* ```--params-file=/some/path/to/foo```Look at absolute path

Thoughts?

**Comment by aradford123** [comment]
I can work with that.  But should that logic apply to snippets too? 
eg. 
--named-filter=foo Look in Params directory under snippets.
--named-filter=./foo look in current directory
--named-filter=/some/path/to/foo absolute path

Also to do-edits to make them consistent?

**Comment by einarnn** [comment]
You raise a good point. It would be consistent behaviour, but not sure. I don't feel strongly. Do you?

**Comment by einarnn** [comment]
Discussed with @aradford123 , we'll leave params files out of the snippets directory for now.
