### ISSUE TITLE
add --hello

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/ncc#7]
I think this might be useful to get a (formatted) list of capabilities.  
Allows people to test authentication too.. 

I suppose they can just issue a --get-running to validate creds too?

**Comment by einarnn** [comment]
Why not make the option `--capabilities`? That requires authentication anyway. Also, if all you want to do is test creds, why wouldn't you just `ssh -p 830 user@host -s netconf`? Although I grant that requires maybe more knowledge than we want people to have to have?

**Comment by aradford123** [comment]
--capabilities works.

The only reason for --hello is 'hello world' the first thing anyone new tries.

No strong view from me.

**Comment by einarnn** [comment]
Now added two new options:

* `--capabilities` - Lists out device capabilities categorized into NETCONF capabilities and various model ecosystems. Only run against IOS-XR so far, so may need enhanced for IOS-XE and NX-OS.
* `--is-supported PY_REGEX` - Query NETCONF server capabilities for YANG modules that matches the provided **Python** regular expression.

All in commit [this](https://github.com/CiscoDevNet/ncc/commit/04124f094c600f62e0cf773cf29c7a245d91379e) commit.
