### ISSUE TITLE
should device creds be read from environment variables to default them

### ISSUE THREAD

**Issue by aradford123** [CiscoDevNet/ncc#8]
Should we provide a way to specify a default device, username, password in ENV variables, a bit like open stack.

Then you can run ncc without creds on the CLI.

You can of course override the device, user, password with appropriate -- options.

Should provide an "init" script to read and set the VARS (for those who are not unix savy).

**Comment by einarnn** [comment]
I'd be happy to have this added, but I don't feel the personal need for it, so I've assigned it to you to fix!

I assume precedence is CLI provided > environment variables > `ncc.py` default?

When it comes to those that are not *nix-savvy, wouldn't they be better providing creds with `-u USER -p PASSWD`? I would actually position this more as something for the more experienced user?

**Comment by aradford123** [comment]
you ok with using configargparse which is a drop in replacement for argparse

configargparse import ArgumentParser

Can just to the following:
parser.add_argument('-u', '--username', type=str, default='cisco', env_var="USERNAME",
                        help="Username to use for SSH authentication (default 'cisco')")
    parser.add_argument('-p', '--password', type=str, default='cisco', env_var="PASSWORD",
                        help="Password to use for SSH authentication (default 'cisco')")

**Comment by aradford123** [comment]
BTW, my preference is to prefix env vars with NCC
NCC_USERNAME
NCC_PASSWORD

maybe even NCC_PORT, NCC_SNIPPETS etc

**Comment by aradford123** [comment]
reverted to just argparse and os.envion.get
Still think NCC_ for prefix?
